name: Deploy static site to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:       # ← this fixes the “Missing environment” error
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .       # or ./docs if that’s where index.html lives

      - id: deploy
        uses: actions/deploy-pages@v4
