name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # If you need Node (React, Vite, etc.). Remove these two if the site is just raw HTML/CSS/JS.
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm ci          # or npm install
          npm run build   # produce static files → ./dist (adjust if different)

      # Upload the built site as an artefact for the deploy job
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist    # change if your build output folder differs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
