name: Deploy static site to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Package/Node steps removed – we just upload the files that are already in the repo
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .          # use ./docs if you keep the site in /docs

      - uses: actions/deploy-pages@v4
        id: deployment
